#!/bin/bash
function update {
	now=$(date +%a+%F+%T)
	echo "Please Specify Your Directory "
    read dir
    echo "I am starting :: Phase 1 looking for updates" | tee -a $dir/$now.log
	sudo apt-get update -y | tee -a $dir/$now.log
	echo "Possible Upgrades :: Phase 2" | tee -a $dir/$now.log
	sudo apt-get upgrade -y | tee -a $dir/$now.log
	sudo apt-get dist-upgrade -y | tee -a $dir/$now.log
	echo "Removing Useless Content :: Phase 3" | tee -a $dir/$now.log
	sudo apt-get autoremove -y | tee -a $dir/$now.log
    sudo apt-get autoclean -y | tee -a $dir/$now.log
	exit
}
function wait {
	while true; do
        update 
        sleep 43200s
    done
}
wait
