#!/bin/bash
function update {
	echo "I am starting :: Phase 1 looking for updates"
	sudo apt-get update -y
	echo "Possible Upgrades :: Phase 2"
	sudo apt-get upgrade -y
	sudo apt-get dist-upgrade -y
	echo "Removing Useless Content :: Phase 3"
	sudo apt-get autoremove 
	sudo apt-get autoclean
	exit
}
function wait {
	while true; do
        update 
        sleep 5s
    done
}
wait

